[features]
seeds = false
skip-lint = false
[programs.localnet]
my_token_project = "FJEYa3zCE6uQ6EpFdK1ad8513WGMRFPm6ikcGE3bZSex"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[provider]
cluster = "https://api.testnet.solana.com"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.30.1"

